"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import sys
import os
import socket

from decouple import Config, RepositoryEnv, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
DJANGO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(DJANGO_ROOT)
SITE_NAME = os.path.basename(DJANGO_ROOT)
PUBLIC_ROOT = os.path.join(PROJECT_ROOT, 'public')
RUN_ROOT = os.path.join(PROJECT_ROOT, 'run')
LOGGING_ROOT = os.path.join(PROJECT_ROOT, 'logs')
LOCALE_ROOT = os.path.join(PROJECT_ROOT, 'locale')
TEMPLATES_ROOT = os.path.join(PROJECT_ROOT, 'templates')

DOTENV_ROOT = os.path.join(RUN_ROOT, '.envs')
DOTENV_FILE = os.path.join(DOTENV_ROOT, f".{os.environ.get('ENVIRONMENT')}", '.env')
env = Config(RepositoryEnv(DOTENV_FILE))

# This allows easy placement of apps within the interior
# src directory.
sys.path.append(os.path.normpath(os.path.join(PROJECT_ROOT, 'apps')))
sys.path.append(os.path.normpath(
    os.path.join(PROJECT_ROOT, 'apps', 'shared_apps')))
# Libraries shared for all projects in the format of templatetags
# and Abstract models
sys.path.append(os.path.normpath(os.path.join(PROJECT_ROOT, 'libs')))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_FILE = os.path.normpath(os.path.join(
    RUN_ROOT,
    f"SECRET_FILE_{os.environ.get('ENVIRONMENT').upper()}.key"))

try:
    SECRET_KEY = open(SECRET_FILE).read().strip()
except IOError:
    try:
        from django.utils.crypto import get_random_string
        CHARS = 'abcdefghijklmnopqrstuvwxyz0123456789!$%&()=+-_'
        SECRET_KEY = get_random_string(50, CHARS)
        with open(SECRET_FILE, 'w') as f:
            f.write(SECRET_KEY)
    except IOError:
        raise Exception(f'Could not open {SECRET_FILE} for writing!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('APP_DEBUG', cast=bool)


ADMINS = [
    ("pssalman", "anton.salman@gmail.com"),
]

MANAGERS = ADMINS

ALLOWED_HOSTS = env('APP_ALLOWED_HOSTS', cast=Csv())


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.admindocs',
    'django.contrib.sitemaps',
]

THIRD_APPS = [
    #'crispy_forms',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    #'rest_framework',
    #'django_celery_beat',
    #'django_celery_results',
    'gunicorn',
    'compressor',
    #'captcha',
    'corsheaders',
    #'rosetta',
]
 
LIBRARY_APPS = [
    'core',
    'xutils',
]

SHARED_APPS = [
    #'users',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_APPS + LIBRARY_APPS + SHARED_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = f'{SITE_NAME}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_ROOT],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = f'{SITE_NAME}.wsgi.application'

LOCAL_IP = str(socket.gethostbyname(socket.gethostname()))

print('hostname: ' + socket.gethostname())
print('hostbyip: ' + LOCAL_IP)

APPEND_SLASH = True

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = env('APP_LANGUAGE_CODE')

TIME_ZONE = env('APP_TIME_ZONE')

USE_I18N = env('APP_USE_I18N', cast=bool)

USE_L10N = env('APP_USE_L10N', cast=bool)

USE_TZ = env('APP_USE_TZ', cast=bool)

gettext_noop = lambda s: s

LANGUAGES = [
    ('ar', gettext_noop('Arabic')),
    ('ca', gettext_noop('Catalan')),
    ('cs', gettext_noop('Czech')),
    ('da', gettext_noop('Danish')),
    ('de', gettext_noop('German')),
    ('en-us', gettext_noop('English')),
    ('el', gettext_noop('Greek')),
    ('es', gettext_noop('Spanish')),
    ('fi', gettext_noop('Finnish')),
    ('fr', gettext_noop('French')),
    ('he', gettext_noop('Hebrew')),
    ('it', gettext_noop('Italian')),
    ('ko', gettext_noop('Korean')),
    ('nl', gettext_noop('Dutch')),
    ('pl', gettext_noop('Polish')),
    ('pt', gettext_noop('Portuguese')),
    ('pt-br', gettext_noop('Brazilian Portuguese')),
    ('ro', gettext_noop('Romanian')),
    ('ru', gettext_noop('Russian')),
    ('sk', gettext_noop('Slovak')),
    ('uk', gettext_noop('Ukrainian')),
    ('zh-cn', gettext_noop('Simplified Chinese')),
]

LANGUAGES_BIDI = ['he', 'ar']

# Tell Django where the project's translation files should be.
LOCALE_PATHS = (
    LOCALE_ROOT,
)

SITE_ID = 1

PREPEND_WWW = env('APP_PREPEND_WWW', cast=bool)

# SECURITY
# ------------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PUBLIC_ROOT, 'static')
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, 'static'),
]

COMPRESS_ROOT = os.path.join(PUBLIC_ROOT, 'compress')
COMPRESS_ENABLED = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PUBLIC_ROOT, 'media')

# one email per XX seconds
LOGLIMIT_RATE = env('APP_LOGLIMIT_RATE', cast=int)

# uses keys to detect which errors are the same
LOGLIMIT_MAX_KEYS = env('APP_LOGLIMIT_MAX_KEYS', cast=int)

# uses cache if it's available
LOGLIMIT_CACHE_PREFIX = env('APP_LOGLIMIT_CACHE_PREFIX')